import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import YAML from "yaml";
import type { FastifyInstance } from "fastify";
import { buildApp } from "../src/app.js";
import { MemoryStore } from "../src/store.js";
import { runAlertStress } from "../load-testing/src/phase6-alert-stress.js";
import { validateReleaseInputs } from "../scripts/phase6-release.mjs";

describe("Phase 6 testing and deployment gates",()=>{let app:FastifyInstance|undefined;let directory:string|undefined;afterEach(async()=>{if(app)await app.close();if(directory)await rm(directory,{recursive:true,force:true});app=undefined;directory=undefined;});
  it("stress-tests the real analytics ingestion and HO command-center contracts",async()=>{directory=await mkdtemp(join(tmpdir(),"sentinel-phase6-"));const key="phase6-analytics-engine-shared-key";app=await buildApp({store:new MemoryStore(),analyticsEngineSharedKey:key,reportExportRoot:directory});await app.listen({host:"127.0.0.1",port:0});const address=app.server.address();if(!address||typeof address==="string")throw new Error("test address unavailable");const evidence=await runAlertStress({baseUrl:`http://127.0.0.1:${address.port}`,userId:"user-global-admin",engineKey:key,tenantId:"omsystems",cameraId:"cam-001",events:20,concurrency:4,outputDirectory:directory,configureRule:true});expect(evidence).toMatchObject({events:20,accepted:20,failed:0,visible:20,passed:true});expect(evidence.visibilityP95Ms).toBeLessThan(5000);},20_000);
  it("requires immutable image, certified scale, client UAT, security approval and a fresh backup",async()=>{directory=await mkdtemp(join(tmpdir(),"sentinel-release-"));const files={scale:join(directory,"scale.json"),uat:join(directory,"uat.json"),security:join(directory,"security.json"),backup:join(directory,"backup.json")};await Promise.all([writeFile(files.scale,JSON.stringify({certification:{productionCertified:true}})),writeFile(files.uat,JSON.stringify({approved:true,approvedBy:"client",approvedAt:new Date().toISOString(),openBlockers:[]})),writeFile(files.security,JSON.stringify({approved:true,approvedBy:"security assessor",approvedAt:new Date().toISOString(),reportReference:"SEC-2026-01",openCritical:0,openHigh:0})),writeFile(files.backup,JSON.stringify({createdAt:new Date().toISOString()}))]);await expect(validateReleaseInputs({imageDigest:`sha256:${"a".repeat(64)}`,scaleEvidence:files.scale,uatSignoff:files.uat,securitySignoff:files.security,backupManifest:files.backup})).resolves.toBeTruthy();await writeFile(files.uat,JSON.stringify({approved:false}));await expect(validateReleaseInputs({imageDigest:`sha256:${"a".repeat(64)}`,scaleEvidence:files.scale,uatSignoff:files.uat,securitySignoff:files.security,backupManifest:files.backup})).rejects.toThrow("UAT");});
  it("ships parseable monitoring discovery, SLO alerts and a Grafana dashboard",async()=>{const source=await readFile("deploy/kubernetes/monitoring.yaml","utf8");const documents=YAML.parseAllDocuments(source).map((item)=>item.toJSON());expect(documents.map((item)=>item.kind)).toEqual(["ServiceMonitor","PrometheusRule","ConfigMap"]);const rules=documents[1].spec.groups.flatMap((group:any)=>group.rules);expect(rules.map((item:any)=>item.alert)).toEqual(expect.arrayContaining(["SentinelControlPlaneDown","SentinelApiErrorBudgetBurn","SentinelApiP95High","SentinelBackpressureActive"]));expect(JSON.parse(documents[2].data["sentinel-control-plane.json"]).panels.length).toBeGreaterThanOrEqual(4);});
  it("packages the checksum-verified free model and requires it for AWS readiness",async()=>{const compose=YAML.parse(await readFile("deploy/aws/docker-compose.aws.yml","utf8"));const dockerfile=await readFile("analytics-engine/Dockerfile","utf8");const service=compose.services["analytics-engine"];expect(service.environment).toMatchObject({PORT:8092,ANALYTICS_REQUIRE_MODELS:"true"});expect(dockerfile).toMatch(/^ENV ANALYTICS_REQUIRE_MODELS=true$/m);expect(dockerfile).toContain("ANALYTICS_MODEL_LICENSES_ACCEPTED=true npm run models:download");expect(dockerfile).toContain("test -f /app/dist/analytics-engine/src/index.js");expect(dockerfile).toContain('CMD ["node", "dist/analytics-engine/src/index.js"]');expect(dockerfile).not.toContain('CMD ["node", "dist/src/index.js"]');});
  it("routes AWS services to the database-ready control plane and fails closed on migration errors",async()=>{const compose=YAML.parse(await readFile("deploy/aws/docker-compose.aws.yml","utf8"));const dockerfile=await readFile("Dockerfile","utf8");const dashboard=compose.services["dashboard"];const control=compose.services["control-plane"];expect(dashboard.environment.CONTROL_PLANE_INTERNAL_URL).toBe("http://control-plane:8080");expect(control.healthcheck.test.join(" ")).toContain("/ready");expect(control.environment.ANALYTICS_ENGINE_URL).toBe("http://analytics-engine:8092");expect(dockerfile).toContain("node scripts/run-migrations.mjs && node dist/src/index.js");expect(dockerfile).not.toContain("node scripts/run-migrations.mjs || true");});
});
