apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-models-pvc
  namespace: sentinel-analytics
  labels:
    app: analytics-engine
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
