'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, FileCheck2, Loader2, RefreshCw, Search, ShieldCheck, XCircle } from 'lucide-react';

type Status = 'compliant' | 'compliant_with_exceptions' | 'provisionally_compliant' | 'non_compliant' | 'incomplete';
type Certificate = { id: string; assessmentId: string; certificateNumber: string; title: string; status: Status; issuedAt?: string | null; expiryDate?: string | null; documentHash?: string | null; signature?: string | null; metadata?: { complianceScore?: number } };
const labels: Record<Status, string> = { compliant: 'Compliant', compliant_with_exceptions: 'Compliant with exceptions', provisionally_compliant: 'Provisionally compliant', non_compliant: 'Non-compliant', incomplete: 'Incomplete' };
const date = (value?: string | null) => value && !Number.isNaN(new Date(value).getTime()) ? new Intl.DateTimeFormat(undefined, { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(value)) : 'Not set';
const expired = (item: Certificate) => Boolean(item.expiryDate && new Date(item.expiryDate).getTime() < Date.now());
const expiringSoon = (item: Certificate) => { if (!item.expiryDate || expired(item)) return false; const days = (new Date(item.expiryDate).getTime() - Date.now()) / 86_400_000; return days <= 30; };

export default function CertificatesPage() {
  const [certificates, setCertificates] = useState<Certificate[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [search, setSearch] = useState(''); const [status, setStatus] = useState<Status | 'all'>('all'); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); setError(null); try { const params = new URLSearchParams(); if (status !== 'all') params.set('status', status); const response = await fetch(`/api/compliance/certificates${params.size ? `?${params}` : ''}`, { cache: 'no-store' }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || 'Unable to load compliance certificates.'); setCertificates(Array.isArray(payload?.data) ? payload.data : []); } catch (cause) { setCertificates([]); setError(cause instanceof Error ? cause.message : 'Unable to load compliance certificates.'); } finally { setLoading(false); setRefreshing(false); } }, [status]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => { const term = search.trim().toLowerCase(); return certificates.filter((certificate) => !term || [certificate.title, certificate.certificateNumber, certificate.assessmentId].some((value) => value.toLowerCase().includes(term))); }, [certificates, search]);
  const active = certificates.filter((item) => !expired(item)).length;
  return <div className="mx-auto max-w-7xl p-6"><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-bold text-gray-900">Compliance certificates</h1><p className="mt-1 text-gray-600">Issued certificates are linked to their assessment and scoped to your organization.</p></div><button onClick={() => void load(true)} disabled={refreshing} className="inline-flex items-center justify-center gap-2 rounded-lg border border-gray-300 px-4 py-2 font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${refreshing ? 'animate-spin' : ''}`} />Refresh</button></div>{error && <div className="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{error}</div>}<div className="mb-6 grid gap-4 sm:grid-cols-3"><Stat label="Issued certificates" value={certificates.length} icon={<FileCheck2 className="h-5 w-5" />} /><Stat label="Current" value={active} icon={<ShieldCheck className="h-5 w-5" />} /><Stat label="Require attention" value={certificates.filter((item) => expired(item) || expiringSoon(item)).length} icon={<AlertTriangle className="h-5 w-5" />} /></div><div className="mb-6 grid gap-3 rounded-xl border border-gray-200 bg-white p-4 sm:grid-cols-[1fr_240px]"><label className="relative"><span className="sr-only">Search certificates</span><Search className="absolute left-3 top-3 h-5 w-5 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search number, title, or assessment ID" className="w-full rounded-lg border border-gray-300 py-2 pl-10 pr-3" /></label><select value={status} onChange={(event) => setStatus(event.target.value as Status | 'all')} className="rounded-lg border border-gray-300 px-3 py-2"><option value="all">All statuses</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{loading ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-blue-600" /></div> : visible.length === 0 ? <div className="rounded-xl border border-dashed border-gray-300 bg-white p-12 text-center"><FileCheck2 className="mx-auto h-10 w-10 text-gray-400" /><p className="mt-3 font-medium text-gray-900">No certificates found</p><p className="mt-1 text-sm text-gray-600">Certificates are issued from a completed compliance assessment.</p></div> : <div className="overflow-hidden rounded-xl border border-gray-200 bg-white"><div className="divide-y divide-gray-100">{visible.map((item) => <CertificateRow key={item.id} certificate={item} />)}</div><div className="border-t border-gray-100 px-5 py-3 text-sm text-gray-500">Showing {visible.length} of {certificates.length} certificates</div></div>}</div>;
}
function CertificateRow({ certificate }: { certificate: Certificate }) { const stale = expired(certificate); const soon = expiringSoon(certificate); const tone = stale || certificate.status === 'non_compliant' ? 'bg-red-50 text-red-800' : certificate.status === 'compliant' ? 'bg-green-50 text-green-800' : 'bg-amber-50 text-amber-800'; return <article className="flex flex-col gap-4 p-5 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${tone}`}>{labels[certificate.status]}</span>{stale && <span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-medium text-red-800">Expired</span>}{soon && <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-800">Expires within 30 days</span>}</div><h2 className="mt-2 font-semibold text-gray-900">{certificate.title}</h2><p className="mt-1 font-mono text-sm text-gray-600">{certificate.certificateNumber}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-gray-500"><span>Issued: {date(certificate.issuedAt)}</span><span>Expires: {date(certificate.expiryDate)}</span>{certificate.documentHash && <span>Integrity hash recorded</span>}</div></div><Link href={`/compliance/assessments/${certificate.assessmentId}`} className="inline-flex shrink-0 items-center justify-center rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">View assessment</Link></article>; }
function Stat({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="rounded-xl border border-gray-200 bg-white p-5"><div className="flex items-center justify-between text-gray-500"><span className="text-sm">{label}</span>{icon}</div><p className="mt-2 text-2xl font-bold text-gray-900">{value}</p></div>; }
