logLevel: info

api: yes
apiAddress: :9997

authMethod: http
authHTTPAddress: http://edge-agent:8090/internal/mediamtx/auth
authHTTPExclude:
  - action: api
  - action: metrics
  - action: pprof

hls: yes
hlsAddress: :8888
hlsVariant: lowLatency
hlsAllowOrigins: ['*']

webrtc: no

pathDefaults:
  sourceOnDemand: yes
  sourceOnDemandStartTimeout: 10s
  sourceOnDemandCloseAfter: 10s

paths: {}

