// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type PagesPageConfig = {
  default: React.ComponentType<any> | ((props: any) => React.ReactNode | Promise<React.ReactNode> | never | void)
  getStaticProps?: (context: any) => Promise<any> | any
  getStaticPaths?: (context: any) => Promise<any> | any
  getServerSideProps?: (context: any) => Promise<any> | any
  getInitialProps?: (context: any) => Promise<any> | any
  /**
   * Segment configuration for legacy Pages Router pages.
   * Validated at build-time by parsePagesSegmentConfig.
   */
  config?: {
    maxDuration?: number
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    regions?: string[]
  }
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/account/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/security">> = Specific
  const handler = {} as typeof import("../../../app/account/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/activity-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity-report">> = Specific
  const handler = {} as typeof import("../../../app/activity-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/ai-quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ai-quality">> = Specific
  const handler = {} as typeof import("../../../app/admin/ai-quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/branch-onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/branch-onboarding">> = Specific
  const handler = {} as typeof import("../../../app/admin/branch-onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/camera-import-export/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/camera-import-export">> = Specific
  const handler = {} as typeof import("../../../app/admin/camera-import-export/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/database/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/database">> = Specific
  const handler = {} as typeof import("../../../app/admin/database/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/ha-topology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ha-topology">> = Specific
  const handler = {} as typeof import("../../../app/admin/ha-topology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/media-gateway-failover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/media-gateway-failover">> = Specific
  const handler = {} as typeof import("../../../app/admin/media-gateway-failover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organization">> = Specific
  const handler = {} as typeof import("../../../app/admin/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/platform/capabilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/platform/capabilities">> = Specific
  const handler = {} as typeof import("../../../app/admin/platform/capabilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/qa/ui-audit/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/qa/ui-audit/[runId]">> = Specific
  const handler = {} as typeof import("../../../app/admin/qa/ui-audit/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/qa/ui-audit/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/qa/ui-audit/compare">> = Specific
  const handler = {} as typeof import("../../../app/admin/qa/ui-audit/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/qa/ui-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/qa/ui-audit">> = Specific
  const handler = {} as typeof import("../../../app/admin/qa/ui-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/recording-failover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recording-failover">> = Specific
  const handler = {} as typeof import("../../../app/admin/recording-failover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/roles">> = Specific
  const handler = {} as typeof import("../../../app/admin/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/signed-configuration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/signed-configuration">> = Specific
  const handler = {} as typeof import("../../../app/admin/signed-configuration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/storage-failover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/storage-failover">> = Specific
  const handler = {} as typeof import("../../../app/admin/storage-failover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/stream-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/stream-settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/stream-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system">> = Specific
  const handler = {} as typeof import("../../../app/admin/system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/zero-touch/diagnostics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/zero-touch/diagnostics">> = Specific
  const handler = {} as typeof import("../../../app/admin/zero-touch/diagnostics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/zero-touch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/zero-touch">> = Specific
  const handler = {} as typeof import("../../../app/admin/zero-touch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/abandoned-objects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/abandoned-objects">> = Specific
  const handler = {} as typeof import("../../../app/analytics/abandoned-objects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/alerts">> = Specific
  const handler = {} as typeof import("../../../app/analytics/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/anpr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/anpr">> = Specific
  const handler = {} as typeof import("../../../app/analytics/anpr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/banking/authorized-persons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/banking/authorized-persons">> = Specific
  const handler = {} as typeof import("../../../app/analytics/banking/authorized-persons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/banking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/banking">> = Specific
  const handler = {} as typeof import("../../../app/analytics/banking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/camera-obstruction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/camera-obstruction">> = Specific
  const handler = {} as typeof import("../../../app/analytics/camera-obstruction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/camera-tamper/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/camera-tamper">> = Specific
  const handler = {} as typeof import("../../../app/analytics/camera-tamper/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/crowd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/crowd">> = Specific
  const handler = {} as typeof import("../../../app/analytics/crowd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/analytics/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/face-recognition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/face-recognition">> = Specific
  const handler = {} as typeof import("../../../app/analytics/face-recognition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/face/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/face">> = Specific
  const handler = {} as typeof import("../../../app/analytics/face/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/fall/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/fall">> = Specific
  const handler = {} as typeof import("../../../app/analytics/fall/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/industrial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/industrial">> = Specific
  const handler = {} as typeof import("../../../app/analytics/industrial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/people/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/people">> = Specific
  const handler = {} as typeof import("../../../app/analytics/people/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/reid/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/reid">> = Specific
  const handler = {} as typeof import("../../../app/analytics/reid/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/rules">> = Specific
  const handler = {} as typeof import("../../../app/analytics/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/tailgating/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/tailgating">> = Specific
  const handler = {} as typeof import("../../../app/analytics/tailgating/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/vehicles">> = Specific
  const handler = {} as typeof import("../../../app/analytics/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/audit/branch-compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit/branch-compliance">> = Specific
  const handler = {} as typeof import("../../../app/audit/branch-compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/audit/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit/health">> = Specific
  const handler = {} as typeof import("../../../app/audit/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/audit/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit/maintenance">> = Specific
  const handler = {} as typeof import("../../../app/audit/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/[id]">> = Specific
  const handler = {} as typeof import("../../../app/compliance/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/assessments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/assessments/[id]">> = Specific
  const handler = {} as typeof import("../../../app/compliance/assessments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/assessments">> = Specific
  const handler = {} as typeof import("../../../app/compliance/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/certificates">> = Specific
  const handler = {} as typeof import("../../../app/compliance/certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/controls/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/controls/[id]">> = Specific
  const handler = {} as typeof import("../../../app/compliance/controls/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/controls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/controls">> = Specific
  const handler = {} as typeof import("../../../app/compliance/controls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/compliance/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/evidence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/evidence">> = Specific
  const handler = {} as typeof import("../../../app/compliance/evidence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/findings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/findings/[id]">> = Specific
  const handler = {} as typeof import("../../../app/compliance/findings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/findings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/findings">> = Specific
  const handler = {} as typeof import("../../../app/compliance/findings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/overview">> = Specific
  const handler = {} as typeof import("../../../app/compliance/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance">> = Specific
  const handler = {} as typeof import("../../../app/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/policies">> = Specific
  const handler = {} as typeof import("../../../app/compliance/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/recording/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/recording">> = Specific
  const handler = {} as typeof import("../../../app/compliance/recording/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/requirements/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/requirements/[id]">> = Specific
  const handler = {} as typeof import("../../../app/compliance/requirements/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/requirements/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/requirements/new">> = Specific
  const handler = {} as typeof import("../../../app/compliance/requirements/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/requirements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/requirements">> = Specific
  const handler = {} as typeof import("../../../app/compliance/requirements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/risks/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/risks/[id]">> = Specific
  const handler = {} as typeof import("../../../app/compliance/risks/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/risks/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/risks/new">> = Specific
  const handler = {} as typeof import("../../../app/compliance/risks/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/risks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/risks">> = Specific
  const handler = {} as typeof import("../../../app/compliance/risks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/control-room/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-room">> = Specific
  const handler = {} as typeof import("../../../app/control-room/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboards">> = Specific
  const handler = {} as typeof import("../../../app/dashboards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/diagnostics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diagnostics">> = Specific
  const handler = {} as typeof import("../../../app/diagnostics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/digital-twin/branches/[branchId]/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/digital-twin/branches/[branchId]/editor">> = Specific
  const handler = {} as typeof import("../../../app/digital-twin/branches/[branchId]/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/digital-twin/branches/[branchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/digital-twin/branches/[branchId]">> = Specific
  const handler = {} as typeof import("../../../app/digital-twin/branches/[branchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/digital-twin/branches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/digital-twin/branches">> = Specific
  const handler = {} as typeof import("../../../app/digital-twin/branches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/digital-twin/buildings/[buildingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/digital-twin/buildings/[buildingId]">> = Specific
  const handler = {} as typeof import("../../../app/digital-twin/buildings/[buildingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/digital-twin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/digital-twin">> = Specific
  const handler = {} as typeof import("../../../app/digital-twin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/evidence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/evidence">> = Specific
  const handler = {} as typeof import("../../../app/evidence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/federation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/federation">> = Specific
  const handler = {} as typeof import("../../../app/federation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/incidents/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incidents/[id]">> = Specific
  const handler = {} as typeof import("../../../app/incidents/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/incidents/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incidents/create">> = Specific
  const handler = {} as typeof import("../../../app/incidents/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incidents">> = Specific
  const handler = {} as typeof import("../../../app/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/infrastructure-twin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/infrastructure-twin">> = Specific
  const handler = {} as typeof import("../../../app/infrastructure-twin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations">> = Specific
  const handler = {} as typeof import("../../../app/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/live-incident/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live-incident/[token]">> = Specific
  const handler = {} as typeof import("../../../app/live-incident/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/alerts">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/amc/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/amc/[id]">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/amc/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/amc/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/amc/new">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/amc/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/amc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/amc">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/amc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/assets/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/assets/[id]">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/assets/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/assets/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/assets/new">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/assets/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/assets">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/compatibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/compatibility">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/compatibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/device-configuration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/device-configuration">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/device-configuration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/device-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/device-management">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/device-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/dvr-nvr-monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/dvr-nvr-monitor">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/dvr-nvr-monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/health">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/predictive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/predictive">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/predictive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/privacy/breaches/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/privacy/breaches/new">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/privacy/breaches/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/privacy/breaches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/privacy/breaches">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/privacy/breaches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/privacy/cameras/[cameraId]/purposes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/privacy/cameras/[cameraId]/purposes">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/privacy/cameras/[cameraId]/purposes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/privacy/cameras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/privacy/cameras">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/privacy/cameras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/privacy/controls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/privacy/controls">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/privacy/controls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/privacy">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/privacy/purposes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/privacy/purposes/new">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/privacy/purposes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/privacy/purposes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/privacy/purposes">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/privacy/purposes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/reports">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/vendors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/vendors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/vendors/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/vendors/new">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/vendors/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/vendors">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/workorders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/workorders/[id]">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/workorders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/workorders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/workorders/new">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/workorders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/workorders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/workorders">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/workorders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mobile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mobile">> = Specific
  const handler = {} as typeof import("../../../app/mobile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modules">> = Specific
  const handler = {} as typeof import("../../../app/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/nbfc-operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nbfc-operations">> = Specific
  const handler = {} as typeof import("../../../app/nbfc-operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/ai-command-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/ai-command-center">> = Specific
  const handler = {} as typeof import("../../../app/operations/ai-command-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/alert-command-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/alert-command-center">> = Specific
  const handler = {} as typeof import("../../../app/operations/alert-command-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/alert-notification-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/alert-notification-policy">> = Specific
  const handler = {} as typeof import("../../../app/operations/alert-notification-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/alerts">> = Specific
  const handler = {} as typeof import("../../../app/operations/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/assets">> = Specific
  const handler = {} as typeof import("../../../app/operations/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/branches/[branchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/branches/[branchId]">> = Specific
  const handler = {} as typeof import("../../../app/operations/branches/[branchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/branches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/branches">> = Specific
  const handler = {} as typeof import("../../../app/operations/branches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/cameras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/cameras">> = Specific
  const handler = {} as typeof import("../../../app/operations/cameras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/device-connectivity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/device-connectivity">> = Specific
  const handler = {} as typeof import("../../../app/operations/device-connectivity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/edge-agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/edge-agents">> = Specific
  const handler = {} as typeof import("../../../app/operations/edge-agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/edge-fleet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/edge-fleet">> = Specific
  const handler = {} as typeof import("../../../app/operations/edge-fleet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/ha-failover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/ha-failover">> = Specific
  const handler = {} as typeof import("../../../app/operations/ha-failover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/infrastructure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/infrastructure">> = Specific
  const handler = {} as typeof import("../../../app/operations/infrastructure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/maintenance">> = Specific
  const handler = {} as typeof import("../../../app/operations/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/media-pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/media-pipeline">> = Specific
  const handler = {} as typeof import("../../../app/operations/media-pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/network">> = Specific
  const handler = {} as typeof import("../../../app/operations/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/observability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/observability">> = Specific
  const handler = {} as typeof import("../../../app/operations/observability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations">> = Specific
  const handler = {} as typeof import("../../../app/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/rca-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/rca-analysis">> = Specific
  const handler = {} as typeof import("../../../app/operations/rca-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/recording/archive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/recording/archive">> = Specific
  const handler = {} as typeof import("../../../app/operations/recording/archive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/recording/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/recording">> = Specific
  const handler = {} as typeof import("../../../app/operations/recording/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/recording/recovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/recording/recovery">> = Specific
  const handler = {} as typeof import("../../../app/operations/recording/recovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/storage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/storage">> = Specific
  const handler = {} as typeof import("../../../app/operations/storage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/ups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/ups">> = Specific
  const handler = {} as typeof import("../../../app/operations/ups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/video-wall/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/video-wall">> = Specific
  const handler = {} as typeof import("../../../app/operations/video-wall/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance">> = Specific
  const handler = {} as typeof import("../../../app/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/playback/bookmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playback/bookmarks">> = Specific
  const handler = {} as typeof import("../../../app/playback/bookmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/playback/synced/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playback/synced">> = Specific
  const handler = {} as typeof import("../../../app/playback/synced/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/portable-camera/enroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portable-camera/enroll">> = Specific
  const handler = {} as typeof import("../../../app/portable-camera/enroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/recordings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recordings">> = Specific
  const handler = {} as typeof import("../../../app/recordings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/role-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/role-dashboard">> = Specific
  const handler = {} as typeof import("../../../app/role-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/security-devices/[deviceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-devices/[deviceId]">> = Specific
  const handler = {} as typeof import("../../../app/security-devices/[deviceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/security-devices/branch-posture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-devices/branch-posture">> = Specific
  const handler = {} as typeof import("../../../app/security-devices/branch-posture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/security-devices/devices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-devices/devices">> = Specific
  const handler = {} as typeof import("../../../app/security-devices/devices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/security-devices/discovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-devices/discovery">> = Specific
  const handler = {} as typeof import("../../../app/security-devices/discovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/security-devices/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-devices/integrations">> = Specific
  const handler = {} as typeof import("../../../app/security-devices/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/security-devices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-devices">> = Specific
  const handler = {} as typeof import("../../../app/security-devices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/security-operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-operations">> = Specific
  const handler = {} as typeof import("../../../app/security-operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/integrations/hikvision/ax-pro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/integrations/hikvision/ax-pro">> = Specific
  const handler = {} as typeof import("../../../app/settings/integrations/hikvision/ax-pro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../../app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/video-search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/video-search">> = Specific
  const handler = {} as typeof import("../../../app/video-search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/video/audio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/video/audio">> = Specific
  const handler = {} as typeof import("../../../app/video/audio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/qa/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qa/compare">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/qa/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/qa/runs/[runId]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qa/runs/[runId]/actions">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/qa/runs/[runId]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/qa/runs/[runId]/artifacts/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qa/runs/[runId]/artifacts/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/qa/runs/[runId]/artifacts/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/qa/runs/[runId]/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qa/runs/[runId]/live">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/qa/runs/[runId]/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/qa/runs/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qa/runs/[runId]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/qa/runs/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/qa/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qa/runs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/qa/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/branches/[id]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/branches/[id]/archive">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/branches/[id]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/branches/[id]/disable/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/branches/[id]/disable">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/branches/[id]/disable/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/branches/[id]/lifecycle-impact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/branches/[id]/lifecycle-impact">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/branches/[id]/lifecycle-impact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/branches/[id]/reactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/branches/[id]/reactivate">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/branches/[id]/reactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/branches/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/branches/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/branches/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/branches/all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/branches/all">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/branches/all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/branches">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/cameras/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/cameras/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/cameras/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/cameras/all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/cameras/all">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/cameras/all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/cameras/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/cameras">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/cameras/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/gateways/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/gateways/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/gateways/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/gateways/all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/gateways/all">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/gateways/all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/gateways/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/gateways">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/gateways/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/system/stream-preference/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/stream-preference">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/system/stream-preference/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/access-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/access-logs">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/access-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/branch-compliance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/branch-compliance">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/branch-compliance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/health">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/maintenance/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/maintenance/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/maintenance/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/maintenance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/maintenance">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/maintenance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/quality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/quality">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/quality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/recording-verification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/recording-verification">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/recording-verification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit/storage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/storage">> = Specific
  const handler = {} as typeof import("../../../app/api/audit/storage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/branches/[id]/cameras/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branches/[id]/cameras">> = Specific
  const handler = {} as typeof import("../../../app/api/branches/[id]/cameras/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branches">> = Specific
  const handler = {} as typeof import("../../../app/api/branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cameras/[id]/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cameras/[id]/snapshot">> = Specific
  const handler = {} as typeof import("../../../app/api/cameras/[id]/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cameras/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cameras/[id]/status">> = Specific
  const handler = {} as typeof import("../../../app/api/cameras/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cameras/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cameras/export">> = Specific
  const handler = {} as typeof import("../../../app/api/cameras/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cameras/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cameras/import">> = Specific
  const handler = {} as typeof import("../../../app/api/cameras/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cameras/import/template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cameras/import/template">> = Specific
  const handler = {} as typeof import("../../../app/api/cameras/import/template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/assessments/[id]/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/assessments/[id]/execute">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/assessments/[id]/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/assessments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/assessments/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/assessments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/assessments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/assessments">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/assessments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/certificates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/certificates/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/certificates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/certificates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/certificates">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/certificates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/certificates/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/certificates/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/certificates/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/controls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/controls">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/controls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/evidence/[id]/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/evidence/[id]/validate">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/evidence/[id]/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/evidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/evidence">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/evidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/findings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/findings">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/findings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/requirements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/requirements">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/requirements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/risks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/risks">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/risks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/compliance/tests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compliance/tests">> = Specific
  const handler = {} as typeof import("../../../app/api/compliance/tests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/control/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/control/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/control/v1/alerts/alert-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/v1/alerts/alert-center">> = Specific
  const handler = {} as typeof import("../../../app/api/control/v1/alerts/alert-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/control/v1/grids/layouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/v1/grids/layouts">> = Specific
  const handler = {} as typeof import("../../../app/api/control/v1/grids/layouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/control/v1/video-wall/configs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/v1/video-wall/configs">> = Specific
  const handler = {} as typeof import("../../../app/api/control/v1/video-wall/configs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/digital-twin/topology/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digital-twin/topology">> = Specific
  const handler = {} as typeof import("../../../app/api/digital-twin/topology/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/live/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live/debug">> = Specific
  const handler = {} as typeof import("../../../app/api/live/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live">> = Specific
  const handler = {} as typeof import("../../../app/api/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/media/snapshot-relay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/snapshot-relay">> = Specific
  const handler = {} as typeof import("../../../app/api/media/snapshot-relay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/observability/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observability/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/observability/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/observability/web-vitals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/observability/web-vitals">> = Specific
  const handler = {} as typeof import("../../../app/api/observability/web-vitals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recording-compliance/[cameraId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recording-compliance/[cameraId]">> = Specific
  const handler = {} as typeof import("../../../app/api/recording-compliance/[cameraId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recording/[cameraId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recording/[cameraId]">> = Specific
  const handler = {} as typeof import("../../../app/api/recording/[cameraId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/recordings/play/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recordings/play">> = Specific
  const handler = {} as typeof import("../../../app/api/recordings/play/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/[deviceId]/command/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/[deviceId]/command">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/[deviceId]/command/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/[deviceId]/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/[deviceId]/events">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/[deviceId]/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/[deviceId]/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/[deviceId]/health">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/[deviceId]/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/[deviceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/[deviceId]">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/[deviceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/branches/[branchId]/posture/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/branches/[branchId]/posture">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/branches/[branchId]/posture/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/discovery/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/discovery/[jobId]">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/discovery/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/discovery/devices/[deviceId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/discovery/devices/[deviceId]/approve">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/discovery/devices/[deviceId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/discovery/devices/[deviceId]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/discovery/devices/[deviceId]/reject">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/discovery/devices/[deviceId]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/discovery/devices/[deviceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/discovery/devices/[deviceId]">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/discovery/devices/[deviceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/discovery/devices/approve-high-confidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/discovery/devices/approve-high-confidence">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/discovery/devices/approve-high-confidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/discovery/devices/delete-pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/discovery/devices/delete-pending">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/discovery/devices/delete-pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/discovery/devices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/discovery/devices">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/discovery/devices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/discovery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/discovery">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/discovery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/integrations/[integrationId]/discover/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/integrations/[integrationId]/discover">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/integrations/[integrationId]/discover/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/integrations/[integrationId]/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/integrations/[integrationId]/events">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/integrations/[integrationId]/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/integrations/[integrationId]/poll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/integrations/[integrationId]/poll">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/integrations/[integrationId]/poll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/integrations/[integrationId]/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/integrations/[integrationId]/test">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/integrations/[integrationId]/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/integrations/hikvision/ax-pro/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/integrations/hikvision/ax-pro">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/integrations/hikvision/ax-pro/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/integrations">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices/overview">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security-devices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security-devices">> = Specific
  const handler = {} as typeof import("../../../app/api/security-devices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/security/posture/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security/posture">> = Specific
  const handler = {} as typeof import("../../../app/api/security/posture/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/talk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/talk">> = Specific
  const handler = {} as typeof import("../../../app/api/talk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/v1/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/v1/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/zero-touch/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/zero-touch/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/zero-touch/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/health">> = Specific
  const handler = {} as typeof import("../../../app/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../pages/_app.tsx
{
  type __IsExpected<Specific extends PagesPageConfig> = Specific
  const handler = {} as typeof import("../../../pages/_app.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../pages/camera-detail.tsx
{
  type __IsExpected<Specific extends PagesPageConfig> = Specific
  const handler = {} as typeof import("../../../pages/camera-detail.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../pages/camera-monitoring.tsx
{
  type __IsExpected<Specific extends PagesPageConfig> = Specific
  const handler = {} as typeof import("../../../pages/camera-monitoring.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}



// Validate ../../../app/analytics/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../../app/analytics/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/audit/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../../app/audit/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compliance/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/compliance">> = Specific
  const handler = {} as typeof import("../../../app/compliance/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/control-room/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/control-room">> = Specific
  const handler = {} as typeof import("../../../app/control-room/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/digital-twin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/digital-twin">> = Specific
  const handler = {} as typeof import("../../../app/digital-twin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/federation/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/federation">> = Specific
  const handler = {} as typeof import("../../../app/federation/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maintenance/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../../app/maintenance/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/operations/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/operations">> = Specific
  const handler = {} as typeof import("../../../app/operations/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
