import { NextResponse } from "next/server";

export async function GET() {
  const headers = [
    "camera_name",
    "ip_address",
    "username",
    "password",
    "vendor",
    "model",
    "onvif_port",
    "rtsp_port",
    "rtsp_path",
    "sub_stream_path",
    "channel",
    "branch_id",
    "location_zone",
    "resolution",
    "fps",
    "ptz",
    "audio",
  ];

  const sampleRows = [
    [
      "Main Entrance 4K Cam",
      "192.168.1.101",
      "admin",
      "Admin@12345",
      "hikvision",
      "DS-2CD2043G2",
      "80",
      "554",
      "/Streaming/Channels/101",
      "/Streaming/Channels/102",
      "1",
      "branch-01",
      "Main Entrance Lobby",
      "3840x2160",
      "25",
      "FALSE",
      "TRUE",
    ],
    [
      "Cash Counter Dome 1",
      "192.168.1.102",
      "admin",
      "Secure#Pass2026",
      "dahua",
      "IPC-HDBW2431E",
      "80",
      "554",
      "/cam/realmonitor?channel=1&subtype=0",
      "/cam/realmonitor?channel=1&subtype=1",
      "1",
      "branch-01",
      "Teller Counter 1",
      "2560x1440",
      "30",
      "FALSE",
      "TRUE",
    ],
    [
      "Vault Corridor PTZ",
      "192.168.1.103",
      "admin",
      "Vault$CP@99",
      "cpplus",
      "CP-VNR-3208",
      "80",
      "554",
      "/cam/realmonitor?channel=1&subtype=0",
      "/cam/realmonitor?channel=1&subtype=1",
      "1",
      "branch-01",
      "Vault Corridor",
      "1920x1080",
      "25",
      "TRUE",
      "FALSE",
    ],
    [
      "Parking Lot Outdoor",
      "192.168.1.104",
      "admin",
      "Uniview#2026",
      "uniview",
      "IPC3234SR3",
      "80",
      "554",
      "/unicast/c1/s0/live",
      "/unicast/c1/s1/live",
      "1",
      "branch-01",
      "Visitor Parking",
      "1920x1080",
      "30",
      "FALSE",
      "FALSE",
    ],
    [
      "ATM Room Perimeter",
      "192.168.1.105",
      "root",
      "AxisRootPass@1",
      "axis",
      "M3046-V",
      "80",
      "554",
      "/axis-media/media.amp",
      "/axis-media/media.amp?resolution=640x480",
      "1",
      "branch-01",
      "24/7 ATM Kiosk",
      "1920x1080",
      "25",
      "FALSE",
      "FALSE",
    ],
  ];

  const csvLines = [
    headers.join(","),
    ...sampleRows.map((row) =>
      row.map((val) => (val.includes(",") || val.includes('"') ? `"${val.replace(/"/g, '""')}"` : val)).join(",")
    ),
  ];

  // Prepend UTF-8 Byte Order Mark (BOM) so Excel opens Arabic, Latin, and special characters cleanly
  const csvContent = "\uFEFF" + csvLines.join("\r\n");

  return new NextResponse(csvContent, {
    status: 200,
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": 'attachment; filename="sentinel-camera-import-template.csv"',
      "Cache-Control": "no-store",
    },
  });
}
