/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.1.2-34-g9b6c8969e0-20260731"
#endif /* AVUTIL_FFVERSION_H */
