import { randomUUID } from "node:crypto";
import type { Pool } from "pg";
import type { ControlPlaneStore } from "../control-plane-store.js";
import type {
  OperationalReportSchedule, OperationalReportRun, OperationalReportArtifact,
  OperationalReportDelivery,
} from "../reporting/types.js";

export class OperationalReportRepository {
  constructor(private readonly pool: Pool) {}
  async listSchedules(tenantId: string) { const result = await this.pool.query("SELECT * FROM operational_report_schedules WHERE tenant_id=$1 ORDER BY name", [tenantId]); return result.rows.map(mapSchedule); }
  async createSchedule(input: Omit<OperationalReportSchedule, "id" | "lastRunAt" | "createdAt" | "updatedAt">) { const result = await this.pool.query(`INSERT INTO operational_report_schedules (id,tenant_id,name,timezone,daily_at,template,formats,recipients,filters,enabled,next_run_at,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`, [randomUUID(), input.tenantId, input.name, input.timezone, input.dailyAt, input.template, input.formats, JSON.stringify(input.recipients), JSON.stringify(input.filters), input.enabled, input.nextRunAt, input.createdBy]); return mapSchedule(result.rows[0]); }
  async updateSchedule(id: string, tenantId: string, updates: Partial<Pick<OperationalReportSchedule, "name" | "timezone" | "dailyAt" | "template" | "formats" | "recipients" | "filters" | "enabled" | "nextRunAt" | "lastRunAt">>) { const result = await this.pool.query(`UPDATE operational_report_schedules SET name=COALESCE($3,name),timezone=COALESCE($4,timezone),daily_at=COALESCE($5,daily_at),template=COALESCE($6,template),formats=COALESCE($7,formats),recipients=COALESCE($8,recipients),filters=COALESCE($9,filters),enabled=COALESCE($10,enabled),next_run_at=COALESCE($11,next_run_at),last_run_at=COALESCE($12,last_run_at),lease_until=NULL,updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING *`, [id, tenantId, updates.name ?? null, updates.timezone ?? null, updates.dailyAt ?? null, updates.template ?? null, updates.formats ?? null, updates.recipients ? JSON.stringify(updates.recipients) : null, updates.filters ? JSON.stringify(updates.filters) : null, updates.enabled ?? null, updates.nextRunAt ?? null, updates.lastRunAt ?? null]); return result.rows[0] ? mapSchedule(result.rows[0]) : undefined; }
  async deleteSchedule(id: string, tenantId: string) { const result = await this.pool.query("DELETE FROM operational_report_schedules WHERE id=$1 AND tenant_id=$2", [id, tenantId]); return Boolean(result.rowCount); }
  async claimDueSchedules(now: string, limit: number) { const result = await this.pool.query(`WITH candidates AS (SELECT id FROM operational_report_schedules WHERE enabled AND next_run_at <= $1 AND (lease_until IS NULL OR lease_until < $1) ORDER BY next_run_at FOR UPDATE SKIP LOCKED LIMIT $2) UPDATE operational_report_schedules schedule SET lease_until=$1::timestamptz + interval '2 minutes' FROM candidates WHERE schedule.id=candidates.id RETURNING schedule.*`, [now, limit]); return result.rows.map(mapSchedule); }
  async createRun(input: Omit<OperationalReportRun, "id" | "status" | "progress" | "attempts" | "nextAttemptAt" | "rowCount" | "summary" | "error" | "startedAt" | "completedAt" | "createdAt" | "updatedAt">) { const result = await this.pool.query(`INSERT INTO operational_report_runs (id,tenant_id,schedule_id,requested_by,template,formats,filters,recipients,max_attempts) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`, [randomUUID(), input.tenantId, input.scheduleId, input.requestedBy, input.template, input.formats, JSON.stringify(input.filters), JSON.stringify(input.recipients), input.maxAttempts]); return mapRun(result.rows[0]); }
  async listRuns(tenantId: string, limit: number) { const result = await this.pool.query("SELECT * FROM operational_report_runs WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT $2", [tenantId, limit]); return result.rows.map(mapRun); }
  async getRun(id: string, tenantId: string) { const result = await this.pool.query("SELECT * FROM operational_report_runs WHERE id=$1 AND tenant_id=$2", [id, tenantId]); return result.rows[0] ? mapRun(result.rows[0]) : undefined; }
  async claimRuns(now: string, limit: number) { const result = await this.pool.query(`WITH candidates AS (SELECT id FROM operational_report_runs WHERE ((status IN ('queued','failed') AND next_attempt_at <= $1) OR (status='running' AND lease_until < $1)) AND attempts < max_attempts ORDER BY next_attempt_at,created_at FOR UPDATE SKIP LOCKED LIMIT $2) UPDATE operational_report_runs run SET status='running',attempts=attempts+1,lease_until=$1::timestamptz + interval '5 minutes',started_at=COALESCE(started_at,now()),updated_at=now() FROM candidates WHERE run.id=candidates.id RETURNING run.*`, [now, limit]); return result.rows.map(mapRun); }
  async updateRun(id: string, updates: Partial<Pick<OperationalReportRun, "status" | "progress" | "nextAttemptAt" | "rowCount" | "summary" | "error" | "startedAt" | "completedAt">>) { const result = await this.pool.query(`UPDATE operational_report_runs SET status=COALESCE($2,status),progress=COALESCE($3,progress),next_attempt_at=COALESCE($4,next_attempt_at),row_count=COALESCE($5,row_count),summary=COALESCE($6,summary),error=$7,started_at=COALESCE($8,started_at),completed_at=COALESCE($9,completed_at),lease_until=CASE WHEN COALESCE($2,status)='running' THEN lease_until ELSE NULL END,updated_at=now() WHERE id=$1 RETURNING *`, [id, updates.status ?? null, updates.progress ?? null, updates.nextAttemptAt ?? null, updates.rowCount ?? null, updates.summary ? JSON.stringify(updates.summary) : null, updates.error ?? null, updates.startedAt ?? null, updates.completedAt ?? null]); return result.rows[0] ? mapRun(result.rows[0]) : undefined; }
  async createArtifact(input: Omit<OperationalReportArtifact, "id" | "createdAt">) { const result = await this.pool.query(`INSERT INTO operational_report_artifacts (id,tenant_id,run_id,format,filename,storage_path,content_type,size_bytes,checksum_sha256,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (run_id,format) DO UPDATE SET filename=EXCLUDED.filename,storage_path=EXCLUDED.storage_path,content_type=EXCLUDED.content_type,size_bytes=EXCLUDED.size_bytes,checksum_sha256=EXCLUDED.checksum_sha256,expires_at=EXCLUDED.expires_at,created_at=now() RETURNING *`, [randomUUID(), input.tenantId, input.runId, input.format, input.filename, input.storagePath, input.contentType, input.sizeBytes, input.checksumSha256, input.expiresAt]); return mapArtifact(result.rows[0]); }
  async listArtifacts(tenantId: string, runId: string) { const result = await this.pool.query("SELECT * FROM operational_report_artifacts WHERE tenant_id=$1 AND run_id=$2 ORDER BY format", [tenantId, runId]); return result.rows.map(mapArtifact); }
  async getArtifact(id: string, tenantId: string) { const result = await this.pool.query("SELECT * FROM operational_report_artifacts WHERE id=$1 AND tenant_id=$2", [id, tenantId]); return result.rows[0] ? mapArtifact(result.rows[0]) : undefined; }
  async enqueueDeliveries(input: Array<{ tenantId: string; runId: string; recipient: string }>) { const result: OperationalReportDelivery[] = []; for (const item of input) { const row = await this.pool.query(`INSERT INTO operational_report_deliveries (id,tenant_id,run_id,recipient) VALUES ($1,$2,$3,$4) ON CONFLICT (run_id,recipient) DO UPDATE SET run_id=EXCLUDED.run_id RETURNING *`, [randomUUID(), item.tenantId, item.runId, item.recipient]); result.push(mapDelivery(row.rows[0])); } return result; }
  async claimDeliveries(now: string, limit: number) { const result = await this.pool.query(`WITH candidates AS (SELECT id FROM operational_report_deliveries WHERE ((status IN ('queued','failed') AND next_attempt_at <= $1) OR (status='processing' AND lease_until < $1)) AND attempts < 5 ORDER BY next_attempt_at FOR UPDATE SKIP LOCKED LIMIT $2) UPDATE operational_report_deliveries delivery SET status='processing',attempts=attempts+1,lease_until=$1::timestamptz + interval '2 minutes',updated_at=now() FROM candidates WHERE delivery.id=candidates.id RETURNING delivery.*`, [now, limit]); return result.rows.map(mapDelivery); }
  async completeDelivery(id: string, result: Parameters<ControlPlaneStore["completeOperationalReportDelivery"]>[1]) { const row = await this.pool.query(`UPDATE operational_report_deliveries SET status=$2,provider_id=COALESCE($3,provider_id),error=$4,next_attempt_at=COALESCE($5,next_attempt_at),lease_until=NULL,delivered_at=CASE WHEN $2='delivered' THEN now() ELSE delivered_at END,updated_at=now() WHERE id=$1 RETURNING *`, [id,result.status,result.providerId ?? null,result.error ?? null,result.nextAttemptAt ?? null]); return row.rows[0] ? mapDelivery(row.rows[0]) : undefined; }
  async listDeliveries(tenantId: string, runId: string) { const result = await this.pool.query("SELECT * FROM operational_report_deliveries WHERE tenant_id=$1 AND run_id=$2 ORDER BY created_at", [tenantId,runId]); return result.rows.map(mapDelivery); }
}

const json = <T>(value: unknown, fallback: T): T => value == null ? fallback : (typeof value === "string" ? JSON.parse(value) : value) as T;
const iso = (value: string | Date) => new Date(value).toISOString();
function mapSchedule(row: any): OperationalReportSchedule { return { id:row.id,tenantId:row.tenant_id,name:row.name,timezone:row.timezone,dailyAt:row.daily_at,template:row.template??"comprehensive",formats:row.formats,recipients:json(row.recipients,[]),filters:json(row.filters,{}),enabled:row.enabled,lastRunAt:row.last_run_at?iso(row.last_run_at):null,nextRunAt:iso(row.next_run_at),createdBy:row.created_by,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at) }; }
function mapRun(row: any): OperationalReportRun { return { id:row.id,tenantId:row.tenant_id,scheduleId:row.schedule_id??null,requestedBy:row.requested_by,status:row.status,template:row.template??"comprehensive",formats:row.formats,filters:json(row.filters,{}),recipients:json(row.recipients,[]),progress:row.progress,attempts:row.attempts,maxAttempts:row.max_attempts,nextAttemptAt:iso(row.next_attempt_at),rowCount:row.row_count??null,summary:json(row.summary,null),error:row.error??null,startedAt:row.started_at?iso(row.started_at):null,completedAt:row.completed_at?iso(row.completed_at):null,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at) }; }
function mapArtifact(row:any):OperationalReportArtifact{return{id:row.id,tenantId:row.tenant_id,runId:row.run_id,format:row.format,filename:row.filename,storagePath:row.storage_path,contentType:row.content_type,sizeBytes:Number(row.size_bytes),checksumSha256:row.checksum_sha256,expiresAt:iso(row.expires_at),createdAt:iso(row.created_at)}}
function mapDelivery(row:any):OperationalReportDelivery{return{id:row.id,tenantId:row.tenant_id,runId:row.run_id,recipient:row.recipient,status:row.status,attempts:row.attempts,nextAttemptAt:iso(row.next_attempt_at),providerId:row.provider_id??null,error:row.error??null,deliveredAt:row.delivered_at?iso(row.delivered_at):null,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)}}
