"use client";

import { useState } from "react";
import { CheckCircle2, ExternalLink, FileText, Loader2, ShieldCheck } from "lucide-react";
import { WorkflowNav } from "@/components/workflow-nav";

type Artifact = { id:string; title:string; evidenceType:string; description?:string|null; fileUrl?:string|null; requirementId?:string|null; controlId?:string|null; collectionDate?:string|null; expiryDate?:string|null; sensitivity?:string; validated:boolean };
const expired = (item:Artifact) => Boolean(item.expiryDate && Date.parse(item.expiryDate)<Date.now());
const date = (value?:string|null) => value&&!Number.isNaN(Date.parse(value))?new Date(value).toLocaleDateString():"Not recorded";

export function EvidenceReviewDesk({ items, filtered, status, onStatus, onVerify, verifyingId, loading, unavailable }: { items:Artifact[]; filtered:Artifact[]; status:string; onStatus:(status:"all"|"pending"|"verified"|"expired")=>void; onVerify:(item:Artifact)=>void; verifyingId:string|null; loading:boolean; unavailable:boolean }) {
  const [selectedId,setSelectedId] = useState("");
  const selected = filtered.find(item=>item.id===selectedId)??filtered.find(item=>!item.validated&&!expired(item))??filtered[0];
  return <>
    <WorkflowNav label="Evidence review stage" value={status} onChange={value=>onStatus(value as "all"|"pending"|"verified"|"expired")} items={[{id:"all",label:"All artifacts",count:unavailable?undefined:items.length},{id:"pending",label:"Needs review",count:unavailable?undefined:items.filter(item=>!item.validated&&!expired(item)).length},{id:"verified",label:"Current",count:items.filter(item=>item.validated&&!expired(item)).length},{id:"expired",label:"Expired",count:items.filter(expired).length}]} />
    <div className="evidence-review-desk" aria-busy={loading}>
      <section className="evidence-review-index"><p className="workflow-kicker">ARTIFACT INDEX</p>{loading?<p className="workflow-empty">Loading governed references…</p>:filtered.map(item=><button type="button" key={item.id} aria-pressed={selected?.id===item.id} onClick={()=>setSelectedId(item.id)}><FileText size={18}/><div><small>{item.evidenceType.replaceAll("_"," ")}</small><strong>{item.title}</strong><span>{expired(item)?"Expired":item.validated?"Verified":"Needs review"}</span></div></button>)}{!loading&&!filtered.length&&<p className="workflow-empty">{unavailable?"Evidence feed unavailable.":"No artifacts match this review stage or filter."}</p>}</section>
      {selected?<><article className="evidence-artifact-reference"><p className="workflow-kicker">GOVERNED REFERENCE / {selected.id}</p><div className="evidence-reference-sheet"><span>{selected.evidenceType.replaceAll("_"," ").toUpperCase()}</span><FileText size={45}/><h2>{selected.title}</h2><p>{selected.description||"No description was recorded for this artifact."}</p><div className="evidence-reference-stamp"><ShieldCheck size={17}/>{expired(selected)?"Validity window ended":selected.validated?"Verified reference":"Awaiting verification"}</div><small>Artifact metadata · open the source to review its content.</small></div><div className="evidence-reference-chain"><div><span>01 / Collected</span><strong>{date(selected.collectionDate)}</strong></div><div><span>02 / Linked</span><strong>{selected.controlId?"Control linked":selected.requirementId?"Requirement linked":"No link recorded"}</strong></div><div><span>03 / Verified</span><strong>{selected.validated?"Yes":"Pending"}</strong></div></div></article><aside className="evidence-review-actions"><p className="workflow-kicker">REVIEW BRIEF</p><h2>Check the proof.</h2><p>Review the source and its governing context before marking this artifact verified.</p><dl><div><dt>Sensitivity</dt><dd>{selected.sensitivity||"internal"}</dd></div><div><dt>Expires</dt><dd>{date(selected.expiryDate)}</dd></div><div><dt>Requirement</dt><dd>{selected.requirementId||"Not linked"}</dd></div><div><dt>Control</dt><dd>{selected.controlId||"Not linked"}</dd></div></dl>{selected.fileUrl?<a className="btn-secondary" href={selected.fileUrl} target="_blank" rel="noopener noreferrer">Open source<ExternalLink size={15}/></a>:<p className="evidence-source-missing">No source URL was registered.</p>}{!selected.validated&&!expired(selected)&&<button type="button" className="btn-primary" disabled={verifyingId!==null} onClick={()=>onVerify(selected)}>{verifyingId===selected.id?<Loader2 size={16} className="animate-spin"/>:<CheckCircle2 size={16}/>}Mark verified</button>}{expired(selected)&&<p className="evidence-source-missing">Register a current artifact to restore valid evidence coverage.</p>}</aside></>:<article className="evidence-artifact-reference"><div className="workflow-empty"><FileText size={40}/><strong>Select an artifact to review its proof.</strong><p>Register a governed reference to start the review workflow.</p></div></article>}
    </div>
  </>;
}
