/**
 * Sentinel Grid Authoritative Master Platform Capability Truth Matrix
 * 
 * Every entry is strictly evaluated against actual implementation evidence in the repository.
 * Rules fail closed: when evidence is missing or uncertain, maturity is DOWNGRADED.
 */

import {
  CapabilityMaturity,
  CapabilityRuntimeState,
  type PlatformCapability,
} from '../../packages/contracts/src/capabilities/capability-types.js';

export const PLATFORM_CAPABILITIES: PlatformCapability[] = [
  // ============================================================================
  // VIDEO DOMAIN
  // ============================================================================
  {
    id: 'video.live_view',
    name: 'Live Video Streaming',
    description: 'Low-latency live video streaming via WebRTC, HLS, and MSE with automatic protocol fallback.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T08:00:00Z',
      verifiedVersion: '1.0.0',
    },
    dependencies: {
      services: ['media-gateway', 'control-plane'],
      infrastructure: ['webrtc-signaling', 'rtsp-demuxer'],
    },
    owner: 'media-team',
    introducedVersion: '0.1.0',
    documentation: 'docs/media/LIVE_STREAMING.md',
  },
  {
    id: 'video.multi_camera_live',
    name: 'Multi-Camera Grid Wall',
    description: 'Dynamic responsive video wall with hardware decoding budget management and multi-tile view.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T08:00:00Z',
    },
    dependencies: {
      services: ['media-gateway'],
      infrastructure: ['webcodecs-decoder'],
    },
    owner: 'frontend-team',
    introducedVersion: '0.1.0',
  },
  {
    id: 'video.recording',
    name: 'Continuous & Event Video Recording',
    description: 'Multi-stream MP4/fMP4 video segmenter with metadata indexing and disk writing.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T08:00:00Z',
    },
    dependencies: {
      services: ['recording-engine'],
      infrastructure: ['posix-storage', 'postgres-index'],
    },
    owner: 'recording-team',
    introducedVersion: '0.1.0',
  },
  {
    id: 'video.playback',
    name: 'Historical Video Playback',
    description: 'Time-seekable video playback with variable speed, frame step, and segment caching.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T08:00:00Z',
    },
    dependencies: {
      services: ['media-gateway', 'recording-engine'],
      infrastructure: ['postgres-index'],
    },
    owner: 'media-team',
    introducedVersion: '0.1.0',
  },
  {
    id: 'video.synchronized_playback',
    name: 'Multi-Camera Synchronized Playback',
    description: 'Multi-stream synchronized historical playback with timeline drift compensation.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T08:00:00Z',
    },
    dependencies: {
      services: ['media-gateway'],
      infrastructure: ['client-clock-sync'],
    },
    limitations: ['Drift compensation accuracy degrades beyond 4 simultaneous 4K streams on low-end hardware.'],
    owner: 'frontend-team',
    introducedVersion: '0.2.0',
  },
  {
    id: 'video.timeline',
    name: 'Interactive Recording Timeline',
    description: 'Visual timeline with motion, alarm, and AI event marker overlays.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'recording-engine'],
    },
    owner: 'frontend-team',
  },
  {
    id: 'video.ptz',
    name: 'PTZ Camera Control',
    description: 'Continuous and absolute pan, tilt, zoom controls with preset and tour management.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'edge-agent'],
      hardware: ['onvif-ptz-camera'],
    },
    owner: 'device-team',
  },
  {
    id: 'video.audio',
    name: 'Audio Stream Monitoring',
    description: 'Audio decoding and real-time level metering for supported camera channels.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: false,
      persistenceImplemented: false,
    },
    verification: {
      unitTests: true,
      integrationTests: false,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['media-gateway'],
      hardware: ['camera-microphone'],
    },
    owner: 'media-team',
  },
  {
    id: 'video.talkback',
    name: 'Two-Way Audio Talkback',
    description: 'Push-to-talk bidirectional audio backchannel from operator console to camera speaker.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: false,
      persistenceImplemented: false,
    },
    verification: {
      unitTests: true,
      integrationTests: false,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['media-gateway'],
      infrastructure: ['webrtc-audio-backchannel'],
      hardware: ['camera-speaker'],
    },
    owner: 'media-team',
  },
  {
    id: 'video.snapshots',
    name: 'High-Resolution Snapshot Capture',
    description: 'On-demand frame capture with watermarking, timestamp burn-in, and instant download.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['media-gateway', 'control-plane'],
    },
    owner: 'media-team',
  },
  {
    id: 'video.bookmarks',
    name: 'Video Timeline Bookmarks',
    description: 'Operator tagged timestamps with notes, priority levels, and incident associations.',
    category: 'VIDEO',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres'],
    },
    owner: 'investigation-team',
  },

  // ============================================================================
  // RECORDING DOMAIN
  // ============================================================================
  {
    id: 'recording.continuous',
    name: 'Continuous 24x7 Recording',
    description: 'Uninterrupted stream recording with configurable chunking and disk space quota enforcement.',
    category: 'RECORDING',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['recording-engine'],
      infrastructure: ['storage-volume'],
    },
    owner: 'recording-team',
  },
  {
    id: 'recording.event',
    name: 'Event-Triggered Recording',
    description: 'Pre-alarm and post-alarm buffer recording upon AI or sensor trigger.',
    category: 'RECORDING',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['recording-engine', 'analytics-engine'],
    },
    owner: 'recording-team',
  },
  {
    id: 'recording.index',
    name: 'High-Speed Recording Segment Index',
    description: 'B-tree indexed database catalog of all recording segments with millisecond precision.',
    category: 'RECORDING',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres'],
    },
    owner: 'recording-team',
  },
  {
    id: 'recording.recovery',
    name: 'Recording Gap Recovery & Edge Backfill',
    description: 'Automatic synchronization and backfill of local edge recordings after network disconnection.',
    category: 'RECORDING',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'edge-agent', 'recording-engine'],
    },
    owner: 'edge-team',
  },
  {
    id: 'recording.continuity_verification',
    name: 'Recording Continuity & Gap Audit',
    description: 'Automated verification that continuously checks for missing timeline gaps and stream loss.',
    category: 'RECORDING',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres'],
    },
    owner: 'compliance-team',
  },
  {
    id: 'recording.retention',
    name: 'Tiered Retention Pruning',
    description: 'Regulatory retention rules (30/90/180 days) with automated disk purging and emergency thresholds.',
    category: 'RECORDING',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'recording-engine'],
    },
    owner: 'compliance-team',
  },
  {
    id: 'recording.storage_failover',
    name: 'Storage Target Failover',
    description: 'Automatic seamless switchover to secondary NAS/SAN mount on primary disk full or I/O failure.',
    category: 'RECORDING',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: false,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['recording-engine'],
      infrastructure: ['secondary-mount'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'recording.archive',
    name: 'Cold Cloud Archive Export',
    description: 'Long-term automated archival of marked incident video to S3/Glacier object storage.',
    category: 'RECORDING',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['s3-compatible-storage'],
    },
    owner: 'storage-team',
  },

  // ============================================================================
  // EVIDENCE DOMAIN
  // ============================================================================
  {
    id: 'evidence.snapshot',
    name: 'Forensic Snapshot Evidence',
    description: 'Immutable cryptographically hashed snapshot records linked to incident investigations.',
    category: 'EVIDENCE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres', 'sha256-hasher'],
    },
    owner: 'investigation-team',
  },
  {
    id: 'evidence.clip',
    name: 'Forensic Video Clip Export',
    description: 'Segment slicing and export with frame boundary alignment and metadata preservation.',
    category: 'EVIDENCE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['recording-engine', 'control-plane'],
    },
    owner: 'investigation-team',
  },
  {
    id: 'evidence.package',
    name: 'Bundled Evidence Package (.zip)',
    description: 'Self-contained legal evidence archive with video, audio, logs, and verification manifest.',
    category: 'EVIDENCE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'investigation-team',
  },
  {
    id: 'evidence.sha256_hash',
    name: 'SHA-256 Cryptographic Hash Verification',
    description: 'Automated checksum generation and continuous integrity validation for all stored evidence items.',
    category: 'EVIDENCE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'security-team',
  },
  {
    id: 'evidence.signed_manifest',
    name: 'Cryptographically Signed Manifest',
    description: 'RSA/Ed25519 digital signature of evidence manifest for court-admissible verification.',
    category: 'EVIDENCE',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['crypto-signing-key'],
    },
    owner: 'security-team',
  },
  {
    id: 'evidence.chain_of_custody',
    name: 'Immutable Chain of Custody Audit Log',
    description: 'Non-repudiable ledger of every user who viewed, exported, downloaded, or shared evidence.',
    category: 'EVIDENCE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres-audit-table'],
    },
    owner: 'compliance-team',
  },
  {
    id: 'evidence.legal_hold',
    name: 'Investigation Legal Hold',
    description: 'Cryptographic lock preventing retention pruning from deleting footage subject to legal hold.',
    category: 'EVIDENCE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'recording-engine'],
    },
    owner: 'compliance-team',
  },
  {
    id: 'evidence.redacted_export',
    name: 'AI Video Redaction & Face Blurring',
    description: 'Automated privacy redaction and bounding box blurring for GDPR/DPDP export compliance.',
    category: 'EVIDENCE',
    maturity: CapabilityMaturity.EXPERIMENTAL,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: false,
      e2eTests: false,
      productionDependencyVerified: false,
    },
    dependencies: {
      services: ['analytics-engine', 'media-gateway'],
      models: ['face-blurring-model'],
    },
    limitations: ['Face blurring accuracy requires manual operator review before court or public release.'],
    owner: 'privacy-team',
  },

  // ============================================================================
  // ANALYTICS DOMAIN
  // ============================================================================
  {
    id: 'analytics.person_detection',
    name: 'Real-Time Person Detection',
    description: 'YOLOv8 deep learning model running local inference to detect and track persons in real time.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['analytics-engine'],
      models: ['yolov8n'],
    },
    owner: 'ai-team',
  },
  {
    id: 'analytics.intrusion',
    name: 'Restricted Zone Intrusion Detection',
    description: 'Polygon boundary spatial containment analytics triggering instant security alarms.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['analytics-engine'],
    },
    owner: 'ai-team',
  },
  {
    id: 'analytics.line_crossing',
    name: 'Virtual Line Crossing Detection',
    description: 'Bidirectional and directional tripwire line crossing detection for perimeter security.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['analytics-engine'],
    },
    owner: 'ai-team',
  },
  {
    id: 'analytics.loitering',
    name: 'Loitering & Dwell Time Analytics',
    description: 'Continuous dwell-time tracking in ATM vestibules and branch perimeter zones.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['analytics-engine'],
    },
    owner: 'ai-team',
  },
  {
    id: 'analytics.crowd',
    name: 'Crowd Density & Queue Length Detection',
    description: 'Branch hall crowd density estimation and counter queue length threshold monitoring.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['analytics-engine'],
      models: ['yolov8n'],
    },
    owner: 'ai-team',
  },
  {
    id: 'analytics.camera_tamper',
    name: 'Camera Tamper & Defocus Detection',
    description: 'Edge-based statistical frame analysis detecting camera movement, blinding, or spray.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['edge-agent', 'analytics-engine'],
    },
    owner: 'edge-team',
  },
  {
    id: 'analytics.camera_obstruction',
    name: 'Camera Obstruction & Dark Frame Detection',
    description: 'Heuristic detection of lens covering, darkness, or loss of visual variance.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['edge-agent'],
    },
    owner: 'edge-team',
  },
  {
    id: 'analytics.anpr',
    name: 'Automatic Number Plate Recognition (ANPR)',
    description: 'Vehicle license plate localization and OCR text extraction with watchlist matching.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['analytics-engine'],
      models: ['anpr-detector', 'anpr-recognizer'],
    },
    limitations: ['Requires minimum 150px plate width and less than 30 degree camera angle for optimal OCR accuracy.'],
    owner: 'ai-team',
  },
  {
    id: 'analytics.face_recognition',
    name: 'Face Recognition & Watchlist Matching',
    description: 'Facial feature extraction and cosine distance matching against enrolled VIP/Watchlist vectors.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.EXPERIMENTAL,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: false,
      e2eTests: false,
      productionDependencyVerified: false,
    },
    dependencies: {
      services: ['analytics-engine'],
      models: ['face-detector', 'face-embedding'],
    },
    limitations: ['Experimental research model. Requires explicit authorization and compliance review.'],
    owner: 'ai-team',
  },
  {
    id: 'analytics.fall_detection',
    name: 'Worker/Elderly Fall Detection',
    description: 'Pose estimation and bounding box aspect ratio dynamics to detect sudden falls.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['analytics-engine'],
      models: ['pose-estimator'],
    },
    owner: 'ai-team',
  },
  {
    id: 'analytics.violence',
    name: 'Physical Violence & Fight Detection',
    description: 'Optical flow and rapid limb acceleration heuristics for detecting violent encounters.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.EXPERIMENTAL,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: false,
      e2eTests: false,
      productionDependencyVerified: false,
    },
    dependencies: {
      services: ['analytics-engine'],
    },
    limitations: ['High false positive rate under low lighting or rapid normal motion.'],
    owner: 'ai-team',
  },
  {
    id: 'analytics.tailgating',
    name: 'Access Control Tailgating Detection',
    description: 'Sequence correlation between badge swipe events and camera person count in airlock doors.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.EXPERIMENTAL,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: false,
      e2eTests: false,
      productionDependencyVerified: false,
    },
    dependencies: {
      services: ['analytics-engine', 'control-plane'],
    },
    owner: 'ai-team',
  },
  {
    id: 'analytics.abandoned_object',
    name: 'Abandoned & Unattended Object Detection',
    description: 'Static foreground blob tracking for bags, boxes, or parcels left in sensitive areas.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['analytics-engine'],
    },
    owner: 'ai-team',
  },
  {
    id: 'analytics.heatmap',
    name: 'Spatial Occupancy Heatmaps',
    description: 'Cumulative footfall and dwell time 2D heatmap matrix generation over floorplans.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['analytics-engine', 'control-plane'],
    },
    owner: 'ai-team',
  },
  {
    id: 'analytics.re_identification',
    name: 'Multi-Camera Person Re-Identification (Re-ID)',
    description: 'Cross-camera visual feature embedding to track person movement across multiple branch cameras.',
    category: 'ANALYTICS',
    maturity: CapabilityMaturity.EXPERIMENTAL,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: false,
      e2eTests: false,
      productionDependencyVerified: false,
    },
    dependencies: {
      services: ['analytics-engine'],
      models: ['osnet-reid'],
    },
    limitations: ['Experimental research model. Requires GPU acceleration and controlled camera lighting.'],
    owner: 'ai-team',
  },

  // ============================================================================
  // HIGH AVAILABILITY (HA) DOMAIN
  // ============================================================================
  {
    id: 'ha.control_plane',
    name: 'Active-Active Control Plane Clustering',
    description: 'Dual-instance control plane failover with distributed heartbeat fencing and session sharing.',
    category: 'HA',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['redis-lock'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'ha.media_failover',
    name: 'Automatic Media Gateway Failover',
    description: 'Automatic stream redirection to healthy media gateway instance during node failure.',
    category: 'HA',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['media-gateway', 'control-plane'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'ha.camera_ownership_lease',
    name: 'Distributed Camera Ownership Lease & Fencing',
    description: 'Redis distributed lease locks preventing dual-recording or split-brain on multi-node clusters.',
    category: 'HA',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['recording-engine', 'control-plane'],
      infrastructure: ['redis'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'ha.recording_failover',
    name: 'Recording Engine N+1 Failover',
    description: 'Standby recording node takes over stream ingest when active recording node heartbeat expires.',
    category: 'HA',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['recording-engine', 'control-plane'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'ha.database_failover',
    name: 'PostgreSQL HA & Read Replica Failover',
    description: 'Connection pool reconnect, replica health probing, and retry loops for database failover.',
    category: 'HA',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      infrastructure: ['postgres-primary', 'postgres-replica'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'ha.redis_failover',
    name: 'Redis Sentinel / Cluster Failover',
    description: 'Automatic client reconnect and master switchover for distributed cache and state store.',
    category: 'HA',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      infrastructure: ['redis'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'ha.event_bus',
    name: 'Distributed Event Bus & Queue HA',
    description: 'Resilient Pub/Sub event distribution across control plane and microservices.',
    category: 'HA',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['redis-pubsub'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'ha.edge_offline_operation',
    name: 'Edge Agent Offline Survivability',
    description: 'Autonomous edge operation during WAN outages with local SQLite event queuing and auto-resync.',
    category: 'HA',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['edge-agent'],
      infrastructure: ['sqlite'],
    },
    owner: 'edge-team',
  },

  // ============================================================================
  // SECURITY DOMAIN
  // ============================================================================
  {
    id: 'security.rbac',
    name: 'Role-Based Access Control (RBAC)',
    description: 'Granular permissions matrix with tenant, branch, and camera-level authorization boundaries.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.abac',
    name: 'Attribute-Based Access Control (ABAC)',
    description: 'Contextual access rules based on time of day, network subnet, and user clearance tags.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.mfa',
    name: 'Multi-Factor Authentication (TOTP)',
    description: 'Time-based one-time password (TOTP RFC 6238) QR code setup, verification, and recovery codes.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.audit_logging',
    name: 'Immutable Security Audit Logging',
    description: 'Structured, append-only security logs capturing all login, stream access, and configuration actions.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres-audit-table'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.oidc',
    name: 'OpenID Connect (OIDC) Single Sign-On',
    description: 'Enterprise SSO integration with Google Workspace, Okta, and generic OIDC IdPs.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'identity-team',
  },
  {
    id: 'security.saml',
    name: 'SAML 2.0 Enterprise Federation',
    description: 'SAML 2.0 Service Provider assertion consumer and signed XML authentication.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'identity-team',
  },
  {
    id: 'security.ldap',
    name: 'LDAP & Active Directory Directory Sync',
    description: 'LDAPS directory synchronization with automatic organizational unit and user group mapping.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'identity-team',
  },
  {
    id: 'security.certificate_management',
    name: 'TLS Certificate Lifecycle & Expiry Alerts',
    description: 'Automated TLS certificate expiry tracking, ACME renewals, and warning alerts before expiration.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.secrets_management',
    name: 'Encrypted Credential & Key Vault',
    description: 'AES-256-GCM encrypted database vault with tenant isolation for camera passwords and API tokens.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['encryption-master-key'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.tpm_attestation',
    name: 'TPM 2.0 Hardware Device Attestation',
    description: 'Hardware-backed TPM 2.0 cryptographic PCR measurement and quote verification for edge gateways.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.NOT_IMPLEMENTED,
    runtime: {
      state: CapabilityRuntimeState.NOT_CONFIGURED,
      reason: 'Physical TPM 2.0 hardware binding and remote attestation verifier not available in container deployment.',
    },
    implementation: {
      backend: false,
      frontend: false,
      api: false,
      persistenceRequired: true,
      persistenceImplemented: false,
    },
    verification: {
      unitTests: false,
      integrationTests: false,
      e2eTests: false,
      productionDependencyVerified: false,
    },
    dependencies: {
      hardware: ['tpm-2.0-chip'],
    },
    limitations: ['Hardware dependency requires dedicated bare-metal edge hardware with provisioned endorsement keys.'],
    owner: 'security-team',
  },
  {
    id: 'security.signed_configuration',
    name: 'Cryptographically Signed Edge Config Bundles',
    description: 'HMAC/RSA signature verification ensuring edge agents only accept untampered configuration files.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'edge-agent'],
    },
    owner: 'security-team',
  },

  // ============================================================================
  // OPERATIONS DOMAIN
  // ============================================================================
  {
    id: 'operations.alert_management',
    name: 'Unified Alert Command Center',
    description: 'Real-time alert triage, acknowledge, assign, resolve, and escalation state machine.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres', 'redis-pubsub'],
    },
    owner: 'operations-team',
  },
  {
    id: 'operations.alert_deduplication',
    name: 'Intelligent Alert Storm Deduplication',
    description: 'Sliding window spatial and temporal alert suppression preventing notification floods.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['redis'],
    },
    owner: 'operations-team',
  },
  {
    id: 'operations.incident_management',
    name: 'Security Incident Case Management',
    description: 'End-to-end incident ticketing, evidence attachment, timeline generation, and resolution signoff.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres'],
    },
    owner: 'operations-team',
  },
  {
    id: 'operations.sop_playbooks',
    name: 'Interactive Standard Operating Procedures (SOP)',
    description: 'Interactive checklist playbooks guiding operators through step-by-step incident response.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'operations-team',
  },
  {
    id: 'operations.maintenance_tickets',
    name: 'Hardware Maintenance & Vendor Dispatch',
    description: 'Automated work order generation on camera/NVR failure with vendor SLA tracking.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres'],
    },
    owner: 'operations-team',
  },
  {
    id: 'operations.sla_tracking',
    name: 'SLO & SLA Compliance Engine',
    description: 'Real-time tracking of camera uptime, stream delivery latency, and incident acknowledgment SLAs.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'operations-team',
  },
  {
    id: 'operations.rca',
    name: 'Root Cause Analysis (RCA) Diagnostic Engine',
    description: 'Rule-based and telemetry-driven root cause diagnostic generator for stream/recording failures.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'operations-team',
  },
  {
    id: 'operations.digital_twin',
    name: 'Branch Spatial Digital Twin',
    description: 'Interactive 2D/3D floorplan visual canvas with camera field-of-view and real-time status overlay.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'frontend-team',
  },
  {
    id: 'operations.operator_analytics',
    name: 'Operator Activity & Audit Analytics',
    description: 'Comprehensive tracking of operator sessions, active camera views, searches, and exports.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres'],
    },
    owner: 'operations-team',
  },

  // ============================================================================
  // EDGE DOMAIN
  // ============================================================================
  {
    id: 'edge.agent',
    name: 'Autonomous Edge Agent Service',
    description: 'Lightweight cross-platform edge daemon managing local camera discovery, RTSP tunnels, and telemetry.',
    category: 'EDGE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['edge-agent'],
    },
    owner: 'edge-team',
  },
  {
    id: 'edge.remote_configuration',
    name: 'Remote Dynamic Configuration Push',
    description: 'Centralized push and hot-reload of edge agent stream parameters, credentials, and scan intervals.',
    category: 'EDGE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'edge-agent'],
    },
    owner: 'edge-team',
  },
  {
    id: 'edge.telemetry',
    name: 'Hardware & System Telemetry Ingestion',
    description: 'Real-time CPU, RAM, disk I/O, network bandwidth, and HDD S.M.A.R.T. telemetry streaming.',
    category: 'EDGE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'edge-agent'],
    },
    owner: 'edge-team',
  },
  {
    id: 'edge.remote_upgrade',
    name: 'Remote Edge Agent Binary OTA Upgrade',
    description: 'Over-the-air binary delta packaging, staged deployment, and atomic process replacement.',
    category: 'EDGE',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'edge-agent'],
    },
    owner: 'edge-team',
  },
  {
    id: 'edge.signed_upgrade',
    name: 'Signed Firmware & Binary Verification',
    description: 'Cryptographic signature checking on edge update payloads before execution.',
    category: 'EDGE',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['edge-agent'],
      infrastructure: ['public-verification-key'],
    },
    owner: 'edge-team',
  },
  {
    id: 'edge.rollback',
    name: 'Automatic Failure Rollback',
    description: 'Automatic binary rollback to previous working version if edge health check fails after upgrade.',
    category: 'EDGE',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['edge-agent'],
    },
    owner: 'edge-team',
  },
  {
    id: 'edge.camera_discovery',
    name: 'ONVIF WS-Discovery & Subnet Scanning',
    description: 'Zero-configuration discovery of IP cameras on local subnet using ONVIF probes and ARP.',
    category: 'EDGE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['edge-agent'],
    },
    owner: 'edge-team',
  },
  {
    id: 'edge.recorder_discovery',
    name: 'DVR/NVR Protocol Discovery',
    description: 'Multi-vendor SDK and protocol discovery for Dahua, Hikvision, CP PLUS, Uniview recorders.',
    category: 'EDGE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['edge-agent'],
    },
    owner: 'edge-team',
  },

  // ============================================================================
  // STORAGE DOMAIN
  // ============================================================================
  {
    id: 'storage.local',
    name: 'Local POSIX Direct Attached Storage',
    description: 'High-throughput direct POSIX block/filesystem storage for continuous recording.',
    category: 'STORAGE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      infrastructure: ['posix-filesystem'],
    },
    owner: 'storage-team',
  },
  {
    id: 'storage.nas',
    name: 'Network Attached Storage (NFS / SMB)',
    description: 'Multi-terabyte network storage integration with connection health monitoring.',
    category: 'STORAGE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      infrastructure: ['nfs-client'],
    },
    owner: 'storage-team',
  },
  {
    id: 'storage.object',
    name: 'S3 & MinIO Object Storage',
    description: 'S3-compatible object storage connector for snapshots, clips, and long-term compliance archives.',
    category: 'STORAGE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      infrastructure: ['s3-api'],
    },
    owner: 'storage-team',
  },
  {
    id: 'storage.retention',
    name: 'Multi-Tier Automated Retention Lifecycle',
    description: 'Automated tiered lifecycle moving active video to compressed cold storage before purge.',
    category: 'STORAGE',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane', 'recording-engine'],
    },
    owner: 'storage-team',
  },

  // ============================================================================
  // INTEGRATION DOMAIN
  // ============================================================================
  {
    id: 'integration.webhooks',
    name: 'Outbound Event Webhooks',
    description: 'Configurable outbound HTTP webhooks with HMAC-SHA256 signature verification and automatic retry.',
    category: 'INTEGRATION',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'integration-team',
  },
  {
    id: 'integration.rest_api',
    name: 'OpenAPI / REST Integration APIs',
    description: 'Comprehensive RESTful API with token authentication and OpenAPI 3.0 schema definitions.',
    category: 'INTEGRATION',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'integration-team',
  },

  // ============================================================================
  // SECURITY DOMAIN
  // ============================================================================
  {
    id: 'security.database_tls',
    name: 'Verified PostgreSQL TLS Transport',
    description: 'Enforced PostgreSQL transport security with CA root verification, hostname checking, and zero insecure fallback.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:00:00Z',
    },
    dependencies: {
      services: ['control-plane', 'backend'],
      infrastructure: ['postgres-tls', 'pki-ca'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.internal_service_tls',
    name: 'Internal Service-to-Service TLS',
    description: 'Mutual and authenticated TLS 1.2+ encryption for cross-host service-to-service communication.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:00:00Z',
    },
    dependencies: {
      services: ['control-plane', 'analytics-engine', 'media-gateway', 'recording-engine'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.certificate_validation',
    name: 'Cryptographic Certificate & Chain Validation',
    description: 'Peer certificate validation against enterprise trusted CAs with revocation checking and SAN matching.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:00:00Z',
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.certificate_expiry_monitoring',
    name: 'Certificate Lifecycle & Expiry Alerts',
    description: 'Automated certificate lifecycle monitoring alerting at 90/60/30/14/7/1 days before expiration.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:00:00Z',
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.device_certificate_trust',
    name: 'Device Certificate Pinning & Trust States',
    description: 'Explicit device certificate trust management with SHA-256 fingerprint pinning for legacy cameras and NVRs.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:00:00Z',
    },
    dependencies: {
      services: ['edge-agent', 'control-plane'],
    },
    owner: 'security-team',
  },
  {
    id: 'security.mtls',
    name: 'Mutual TLS (mTLS) Authentication',
    description: 'Client certificate authentication for high-assurance Edge-to-Control Plane and DB links.',
    category: 'SECURITY',
    maturity: CapabilityMaturity.BETA,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: false,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:00:00Z',
    },
    dependencies: {
      services: ['control-plane', 'edge-agent'],
    },
    owner: 'security-team',
  },

  // ============================================================================
  // OPERATIONS / PLATFORM DOMAIN
  // ============================================================================
  {
    id: 'platform.externalized_configuration',
    name: 'Authoritative Externalized Configuration',
    description: 'Zero-localhost externalized configuration management across all distributed Sentinel Grid services.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:45:00Z',
    },
    dependencies: {
      services: ['control-plane', 'media-gateway', 'recording-engine', 'analytics-engine'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'platform.production_config_validation',
    name: 'Production Startup Configuration & Loopback Guard',
    description: 'Fails fast at startup if mandatory endpoints are missing or point to unapproved loopback addresses in production.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:45:00Z',
    },
    dependencies: {
      services: ['control-plane'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'platform.service_discovery',
    name: 'Dynamic Service & Gateway Node Discovery',
    description: 'Dynamic Redis/etcd-backed service registry for multi-node Media Gateway and Recording Engine clusters.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:45:00Z',
    },
    dependencies: {
      services: ['control-plane', 'media-gateway', 'recording-engine'],
    },
    owner: 'infrastructure-team',
  },
  {
    id: 'platform.ha_endpoint_configuration',
    name: 'HA Service Virtual IP & SAN Endpoint Routing',
    description: 'PostgreSQL HA and Redis Cluster endpoint resolution with transparent failover and zero hardcoded node IPs.',
    category: 'OPERATIONS',
    maturity: CapabilityMaturity.PRODUCTION,
    runtime: { state: CapabilityRuntimeState.HEALTHY },
    implementation: {
      backend: true,
      frontend: true,
      api: true,
      persistenceRequired: true,
      persistenceImplemented: true,
    },
    verification: {
      unitTests: true,
      integrationTests: true,
      e2eTests: true,
      productionDependencyVerified: true,
      lastVerifiedAt: '2026-09-02T16:45:00Z',
    },
    dependencies: {
      services: ['control-plane'],
      infrastructure: ['postgres-ha', 'redis-cluster'],
    },
    owner: 'infrastructure-team',
  },
];


