apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinel
resources:
  - namespace.yaml
  - control-plane.yaml
  - autoscaling.yaml
  - network-policy.yaml
  - maintenance.yaml
